### ISSUE TITLE
cli

### ISSUE THREAD

**Issue by chiptus** [EyalPerry/dev-cv#2]
nice idea. 

What about creating a CLI? you give it the json and get the pdf? maybe can add also a template html?

**Comment by EyalPerry** [comment]
Closing due to lack of response.
OP may continue conversation at any point- reopening will be considered accordingly.

**Comment by chiptus** [comment]
Now, to make the CV, I need to clone the repo, and run it.
I would like to have some cli that we can install using `npm i dev-cv` and then I can run:
`dev-cv --template=<template-file> details.json`

**Comment by EyalPerry** [comment]
Do note that ATM, while you indeed need to clone and run the project, the customization is maximized for those with React / SCSS prowess.. How do you imagine this template file would look like, such that it will enable the same customization level?
