### ISSUE TITLE
Projects are not rendered?

### ISSUE THREAD

**Issue by tunnckoCore** [EyalPerry/dev-cv#3]
Heya! Cool one man :tada: Looks kinda great and have an idea behind it.
But to point it out, it does not render the `details.experience[x].projects` items.

**Comment by EyalPerry** [comment]
Hey man, I am glad you like it and thanks for taking the time to point this out. However- this issue is stated at the Known Issues section. The projects feature is a WIP, and is partially implemented :)

**Comment by tunnckoCore** [comment]
Aaah damn, sorry man! :laughing: Why I always miss such parts, hm.

Btw, do you know about the enhancv.com, it can be at least for inspiration. It also features regularly successful resumes, so the designs and ideas are tested.

_(I'm not an affiliate or such, just cool resource)_ :)

**Comment by EyalPerry** [comment]
Happens to the best of us :)
Thanks for the link, I'll check it out.
