### ISSUE TITLE
Use full width when there is nothing in column one

### ISSUE THREAD

**Issue by xni06** [EyalPerry/dev-cv#4]
Example shows two columns - one for the contact details, photo, links etc. and the other for experience. For CV's with lots of experience, subsequent pages show an empty 1st column.

Is it possible for the second column to expand to take up the whole width of the page?

**Comment by EyalPerry** [comment]
@xni06 I have adressed the issue, have a look at the new cv.json layout. you now have full control of what appears where on a page.
